### ISSUE TITLE
filed named "fisher_20000.bn" not found

### ISSUE THREAD

**Issue by momoirene** [ozansener/active_learning_coreset#1]
Dear author:
When I run your code "main.py" under the folder of additional_baselines, there exists an error that "can not find the file named 'fisher_20000.bn' ". And I couldn't  find any code files to create that file. Could you please tell me the procedure that you produce this file? Thank you very much.

**Comment by ozansener** [comment]
Hello,

That file is simply the feature representation (fc layer) of all points concatenated. It is later pickled. I will upload the code which generated it and update the issue.

In the mean time; some folks re-implemented our method in (
https://github.com/google/active-learning/blob/master/sampling_methods/kcenter_greedy.py) And, it is significantly simpler and nicer code.
