### ISSUE TITLE
Running the package

### ISSUE THREAD

**Issue by mfaraki** [ozansener/active_learning_coreset#5]
Hi,
Just wondering if you could specify how to run the package and reproduce the results. From your paper I understand that the implementation is in Tensorflow. So probably for cifar10 that is tf_base -> cifar10_train -> train_cifar ?

There is implementation in PyTorch additional_baselines -> main as well. Is that just re-implementation in PyTorch?

**Comment by alex-zyk** [comment]
Same question. Could you guys provide more details about how to reproduce your results? Thank you!

**Comment by linlinlin1993** [comment]
Hi, could you please provide how to reproduce the results? Such as the "settings.json" file, thanks a lot

**Comment by ozansener** [comment]
Please use the code from: https://github.com/google/active-learning/blob/master/sampling_methods/kcenter_greedy.py We are not supporting this anymore.
